[evol] XIVO_NAMESERVERS variable must be facultative (not defined when using webi/sysconfd)
git-svn-id: https://rcs.lan.proformatique.com/svn/xivo/trunk@7847 dc85baef-7018-0410-bfbd-8a639da648bb

diff --git a/base-config/sbin/pf-common-read-config b/base-config/sbin/pf-common-read-config
--- a/base-config/sbin/pf-common-read-config
+++ b/base-config/sbin/pf-common-read-config
@@ -38,9 +38,10 @@ if [ -n "${XIVO_NAMESERVERS}" ]; then
   for NS in ${XIVO_NAMESERVERS}; do
     XIVO_NAMESERVER_LIST="${XIVO_NAMESERVER_LIST}nameserver ${NS}\n"
   done
-else
-  echo "ERROR: no nameservers defined" >&2
-  exit 1
+# XIVO_NAMESERVERS
+#else
+#  echo "ERROR: no nameservers defined" >&2
+#  exit 1
 fi
 
 XIVO_DHCP_IFACES="none"
