[evol] use common config mechanism now (from Dalek)
git-svn-id: https://rcs.lan.proformatique.com/svn/xivo/trunk@7373 dc85baef-7018-0410-bfbd-8a639da648bb

diff --git a/base-config/sbin/update-pf-xivo-base-config b/base-config/sbin/update-pf-xivo-base-config
--- a/base-config/sbin/update-pf-xivo-base-config
+++ b/base-config/sbin/update-pf-xivo-base-config
@@ -8,64 +8,7 @@
 BASE_TEMPLATE_DIR=/usr/share/pf-xivo-base-config/templates
 CUSTOM_TEMPLATE_DIR=/etc/pf-xivo/custom-templates
 
-. /etc/pf-xivo/common.conf
-
-
-# TODO: use the _XIVO_* namespace for generated variables
-
-
-echo "Generating configuration"
-
-#### Set and check general variables ####
-
-if [ -z "${XIVO_NET4_CIDR}" ]; then
-  echo "ERROR: Network badly configured" >&2
-  exit 1
-fi
-
-XIVO_NET4_IP=$(ipcalc -n ${XIVO_NET4_CIDR} | grep "Address:" | awk '{print $2}')
-XIVO_NET4_NETMASK=$(ipcalc -n ${XIVO_NET4_CIDR} | grep "Netmask:" | awk '{print $2}')
-XIVO_NET4_BROADCAST=$(ipcalc -n ${XIVO_NET4_CIDR} | grep "Broadcast:" | awk '{print $2}')
-XIVO_NET4_SUBNET=$(ipcalc -n ${XIVO_NET4_CIDR} | grep "Network:" | awk '{print $2}' | cut -d/ -f1)
-
-if [ -z "${XIVO_VOIP_VLAN_ID}" -o "${XIVO_VOIP_VLAN_ID}" = "0" ]; then
-  XIVO_HAS_VOIP_VLAN_10=0
-  XIVO_HAS_VOIP_VLAN_yn="no"
-else
-  XIVO_HAS_VOIP_VLAN_10=1
-  XIVO_HAS_VOIP_VLAN_yn="yes"
-fi
-
-if [ -z "${XIVO_SMTP_ORIGIN}" ]; then
-  XIVO_SMTP_ORIGIN="${XIVO_HOSTNAME}.${XIVO_DOMAIN}"
-fi
-
-XIVO_NAMESERVER_LIST=
-if [ -n "${XIVO_NAMESERVERS}" ]; then
-  for NS in ${XIVO_NAMESERVERS}; do
-    XIVO_NAMESERVER_LIST="${XIVO_NAMESERVER_LIST}nameserver ${NS}\n"
-  done
-else
-  echo "ERROR: no nameservers defined" >&2
-  exit 1
-fi
-
-if [ -n "${XIVO_DHCP_POOL}" ]; then
-  _XIVO_DHCP_SUBNET="\# Include of the subnet declaration (XIVO_DHCP_POOL is not void in common.conf)\ninclude \"/etc/dhcp3/dhcpd_subnet.conf\";"
-else
-  _XIVO_DHCP_SUBNET="\# Subnet declaration not specified because XIVO_DHCP_POOL is void in common.conf\n\# Use dhcpd_extra.conf for custom configuration"
-fi
-
-if [ "${XIVO_MAINTENANCE}" = "1" ]; then
-  ALERT_EMAILS="${ALERT_EMAILS} pv-tech-xivo-alerts+${XIVO_HOSTNAME}@lists.proformatique.com"
-  XIVO_SMTP_CANONICAL="root\tpv-tech-xivo-reports+${XIVO_HOSTNAME}+root@lists.proformatique.com\nasterisk\tpv-tech-xivo-reports+${XIVO_HOSTNAME}+asterisk@lists.proformatique.com\n${XIVO_SMTP_CANONICAL}"
-fi
-
-if [ -n "${XIVO_SMTP_MYDOMAIN}" ]; then
-  _XIVO_SMTP_MYDOMAIN=${XIVO_SMTP_DOMAIN}
-else
-  _XIVO_SMTP_MYDOMAIN=${XIVO_DOMAIN}
-fi
+. /usr/sbin/pf-common-read-config
 
 # list all variables with the good prefix
 TEMPLATE_VARS="$(compgen -v XIVO_) $(compgen -v _XIVO_)"
@@ -156,8 +99,10 @@ do_apply()
   local RESULT_SUBDIR=${RESULT_DIR}/${CONFIG_NAME}
   # if SYSTEM_DIR is empty, install into /
 
-  if grep -qEr "#[A-Z0-9_]+#" ${RESULT_SUBDIR}; then
-    echo "ERROR: generation from template '${CONFIG_NAME}' failed (all variables could not be expanded)" >&2
+  NOT_EXPANDED=$(grep -Er "#[A-Z0-9_]+#" ${RESULT_SUBDIR})
+  if [ -n "${NOT_EXPANDED}" ]; then
+    echo "ERROR: generation from template '${CONFIG_NAME}' failed because all variables could not be expanded:" >&2
+    echo ${NOT_EXPANDED} | cut -d: -f2-
     return 1
   fi
 
