Création de la distribution PtitQUICC, pour tester le port sur PowerPC.
git-svn-id: https://rcs.lan.proformatique.com/svn/xivo/trunk@99 dc85baef-7018-0410-bfbd-8a639da648bb

diff --git a/build-system/patches/php-4.4.4_crosscompile.patch b/build-system/patches/php-4.4.4_crosscompile.patch
--- a/build-system/patches/php-4.4.4_crosscompile.patch
+++ b/build-system/patches/php-4.4.4_crosscompile.patch
@@ -1,6 +1,6 @@
-diff -Nurp php-4.4.2.orig/build/libtool.m4 php-4.4.2/build/libtool.m4
---- php-4.4.2.orig/build/libtool.m4	2005-12-19 23:29:12.000000000 +0100
-+++ php-4.4.2/build/libtool.m4	2006-07-13 14:00:25.000000000 +0200
+diff -Nurp php-4.4.4.orig/build/libtool.m4 php-4.4.4/build/libtool.m4
+--- php-4.4.4.orig/build/libtool.m4	2005-12-19 23:29:12.000000000 +0100
++++ php-4.4.4/build/libtool.m4	2006-08-31 15:14:32.000000000 +0200
 @@ -778,6 +778,7 @@ fi
  # Transform linux* to *-*-linux-gnu*, to support old configure scripts.
  case $host_os in
@@ -27,9 +27,9 @@ diff -Nurp php-4.4.2.orig/build/libtool.m4 php-4.4.2/build/libtool.m4
    case $host_cpu in
    alpha* | hppa* | i*86 | mips | mipsel | powerpc* | sparc* | ia64* | s390* | x86_64*)
      lt_cv_deplibs_check_method=pass_all ;;
-diff -Nurp php-4.4.2.orig/config.sub php-4.4.2/config.sub
---- php-4.4.2.orig/config.sub	2005-02-15 09:52:33.000000000 +0100
-+++ php-4.4.2/config.sub	2006-07-13 14:00:25.000000000 +0200
+diff -Nurp php-4.4.4.orig/config.sub php-4.4.4/config.sub
+--- php-4.4.4.orig/config.sub	2005-02-15 09:52:33.000000000 +0100
++++ php-4.4.4/config.sub	2006-08-31 15:14:32.000000000 +0200
 @@ -118,7 +118,7 @@ esac
  # Here we must recognize all the valid KERNEL-OS combinations.
  maybe_os=`echo $1 | sed 's/^\(.*\)-\([^-]*-[^-]*\)$/\2/'`
@@ -48,9 +48,9 @@ diff -Nurp php-4.4.2.orig/config.sub php-4.4.2/config.sub
  	      | -interix* | -uwin* | -mks* | -rhapsody* | -darwin* | -opened* \
  	      | -openstep* | -oskit* | -conix* | -pw32* | -nonstopux* \
  	      | -storm-chaos* | -tops10* | -tenex* | -tops20* | -its* \
-diff -Nurp php-4.4.2.orig/configure php-4.4.2/configure
---- php-4.4.2.orig/configure	2006-01-12 19:24:23.000000000 +0100
-+++ php-4.4.2/configure	2006-07-13 14:00:36.000000000 +0200
+diff -Nurp php-4.4.4.orig/configure php-4.4.4/configure
+--- php-4.4.4.orig/configure	2006-08-15 14:01:18.000000000 +0200
++++ php-4.4.4/configure	2006-08-31 15:14:40.000000000 +0200
 @@ -12285,8 +12285,8 @@ EOF
  
  
@@ -117,7 +117,65 @@ diff -Nurp php-4.4.2.orig/configure php-4.4.2/configure
  
      LIBS=$ac_libs
    fi
-@@ -100349,7 +100349,7 @@ irix5* | irix6* | nonstopux*)
+@@ -14357,55 +14357,8 @@ rm -f conftest*
+         cookie_io_functions_t=cookie_io_functions_t
+         have_fopen_cookie=yes
+ 
+-		
+-		if test "$cross_compiling" = yes; then
+-    { echo "configure: error: can not run test program while cross compiling" 1>&2; exit 1; }
+-else
+-  cat > conftest.$ac_ext <<EOF
+-#line 14366 "configure"
+-#include "confdefs.h"
+-
+-#define _GNU_SOURCE
+-#include <stdio.h>
+-
+-struct cookiedata {
+-	__off64_t pos;
+-};
+-
+-__ssize_t reader(void *cookie, char *buffer, size_t size)
+-{ return size; }
+-__ssize_t writer(void *cookie, const char *buffer, size_t size)
+-{ return size; }
+-int closer(void *cookie)
+-{ return 0; }
+-int seeker(void *cookie, __off64_t *position, int whence)
+-{ ((struct cookiedata*)cookie)->pos = *position; return 0; }
+-
+-cookie_io_functions_t funcs = {reader, writer, seeker, closer};
+-
+-main() {
+-  struct cookiedata g = { 0 };
+-  FILE *fp = fopencookie(&g, "r", funcs);
+-
+-  if (fp && fseek(fp, 8192, SEEK_SET) == 0 && g.pos == 8192)
+-	  exit(0);
+-  exit(1);
+-}
+-
+-					   
+-EOF
+-if { (eval echo configure:14398: \"$ac_link\") 1>&5; (eval $ac_link) 2>&5; } && test -s conftest${ac_exeext} && (./conftest; exit) 2>/dev/null
+-then
+-   cookie_io_functions_use_off64_t=yes 
+-else
+-  echo "configure: failed program was:" >&5
+-  cat conftest.$ac_ext >&5
+-  rm -fr conftest*
+-    
+-fi
+-rm -fr conftest*
+-fi
+-
++        # Dirty hack...
++        cookie_io_functions_use_off64_t=yes 
+ 		
+       else
+   	            		    cat > conftest.$ac_ext <<EOF
+@@ -100349,7 +100302,7 @@ irix5* | irix6* | nonstopux*)
    ;;
  
  # This must be Linux ELF.
@@ -126,7 +184,7 @@ diff -Nurp php-4.4.2.orig/configure php-4.4.2/configure
    case $host_cpu in
    alpha* | hppa* | i*86 | mips | mipsel | powerpc* | sparc* | ia64* | s390* | x86_64*)
      lt_cv_deplibs_check_method=pass_all ;;
-@@ -100960,7 +100960,7 @@ fi
+@@ -100960,7 +100913,7 @@ fi
  fi
  
  
@@ -135,7 +193,7 @@ diff -Nurp php-4.4.2.orig/configure php-4.4.2/configure
  enable_win32_dll=no
  
  # Check whether --enable-libtool-lock or --disable-libtool-lock was given.
-@@ -101101,6 +101101,7 @@ fi
+@@ -101101,6 +101054,7 @@ fi
  # Transform linux* to *-*-linux-gnu*, to support old configure scripts.
  case $host_os in
  linux-gnu*) ;;
@@ -143,7 +201,7 @@ diff -Nurp php-4.4.2.orig/configure php-4.4.2/configure
  linux*) host=`echo $host | sed 's/^\(.*-.*-linux\)\(.*\)$/\1-gnu\2/'`
  esac
  
-@@ -102577,7 +102578,7 @@ linux-gnuoldld* | linux-gnuaout* | linux
+@@ -102577,7 +102531,7 @@ linux-gnuoldld* | linux-gnuaout* | linux
    ;;
  
  # This must be Linux ELF.
@@ -152,9 +210,9 @@ diff -Nurp php-4.4.2.orig/configure php-4.4.2/configure
    version_type=linux
    need_lib_prefix=no
    need_version=no
-diff -Nurp php-4.4.2.orig/ext/standard/basic_functions.c php-4.4.2/ext/standard/basic_functions.c
---- php-4.4.2.orig/ext/standard/basic_functions.c	2006-01-01 14:46:57.000000000 +0100
-+++ php-4.4.2/ext/standard/basic_functions.c	2006-07-13 14:00:25.000000000 +0200
+diff -Nurp php-4.4.4.orig/ext/standard/basic_functions.c php-4.4.4/ext/standard/basic_functions.c
+--- php-4.4.4.orig/ext/standard/basic_functions.c	2006-06-29 00:09:09.000000000 +0200
++++ php-4.4.4/ext/standard/basic_functions.c	2006-08-31 15:14:33.000000000 +0200
 @@ -438,7 +438,9 @@ function_entry basic_functions[] = {
  
  #if HAVE_RES_SEARCH && !(defined(__BEOS__) || defined(PHP_WIN32) || defined(NETWARE))
@@ -165,9 +223,9 @@ diff -Nurp php-4.4.2.orig/ext/standard/basic_functions.c php-4.4.2/ext/standard/
  #endif
  
  	PHP_FE(getmyuid,														NULL)
-diff -Nurp php-4.4.2.orig/ext/standard/dns.c php-4.4.2/ext/standard/dns.c
---- php-4.4.2.orig/ext/standard/dns.c	2006-01-01 14:46:57.000000000 +0100
-+++ php-4.4.2/ext/standard/dns.c	2006-07-13 14:00:25.000000000 +0200
+diff -Nurp php-4.4.4.orig/ext/standard/dns.c php-4.4.4/ext/standard/dns.c
+--- php-4.4.4.orig/ext/standard/dns.c	2006-01-01 14:46:57.000000000 +0100
++++ php-4.4.4/ext/standard/dns.c	2006-08-31 15:14:33.000000000 +0200
 @@ -275,6 +275,7 @@ PHP_FUNCTION(checkdnsrr)
  #define MAXHOSTNAMELEN  256
  #endif /* MAXHOSTNAMELEN */
@@ -184,9 +242,9 @@ diff -Nurp php-4.4.2.orig/ext/standard/dns.c php-4.4.2/ext/standard/dns.c
  
  #endif
  /*
-diff -Nurp php-4.4.2.orig/Zend/zend_API.c php-4.4.2/Zend/zend_API.c
---- php-4.4.2.orig/Zend/zend_API.c	2006-01-01 14:46:49.000000000 +0100
-+++ php-4.4.2/Zend/zend_API.c	2006-07-13 14:00:25.000000000 +0200
+diff -Nurp php-4.4.4.orig/Zend/zend_API.c php-4.4.4/Zend/zend_API.c
+--- php-4.4.4.orig/Zend/zend_API.c	2006-07-22 17:48:22.000000000 +0200
++++ php-4.4.4/Zend/zend_API.c	2006-08-31 15:14:33.000000000 +0200
 @@ -30,6 +30,10 @@
  #include <stdarg.h>
  #endif
@@ -198,9 +256,9 @@ diff -Nurp php-4.4.2.orig/Zend/zend_API.c php-4.4.2/Zend/zend_API.c
  /* these variables are true statics/globals, and have to be mutex'ed on every access */
  static int module_count=0;
  ZEND_API HashTable module_registry;
-diff -Nurp php-4.4.2.orig/Zend/zend_builtin_functions.c php-4.4.2/Zend/zend_builtin_functions.c
---- php-4.4.2.orig/Zend/zend_builtin_functions.c	2006-01-01 14:46:49.000000000 +0100
-+++ php-4.4.2/Zend/zend_builtin_functions.c	2006-07-13 14:00:25.000000000 +0200
+diff -Nurp php-4.4.4.orig/Zend/zend_builtin_functions.c php-4.4.4/Zend/zend_builtin_functions.c
+--- php-4.4.4.orig/Zend/zend_builtin_functions.c	2006-01-01 14:46:49.000000000 +0100
++++ php-4.4.4/Zend/zend_builtin_functions.c	2006-08-31 15:14:33.000000000 +0200
 @@ -72,6 +72,10 @@ static ZEND_FUNCTION(debug_backtrace);
  static ZEND_FUNCTION(zend_test_func);
  #endif
@@ -212,9 +270,9 @@ diff -Nurp php-4.4.2.orig/Zend/zend_builtin_functions.c php-4.4.2/Zend/zend_buil
  ZEND_API unsigned char first_arg_force_ref[] = { 1, BYREF_FORCE };
  ZEND_API unsigned char second_arg_force_ref[] = { 2, BYREF_NONE, BYREF_FORCE };
  ZEND_API unsigned char third_arg_force_ref[] = { 3, BYREF_NONE, BYREF_NONE, BYREF_FORCE };
-diff -Nurp php-4.4.2.orig/Zend/zend_compile.c php-4.4.2/Zend/zend_compile.c
---- php-4.4.2.orig/Zend/zend_compile.c	2006-01-01 14:46:49.000000000 +0100
-+++ php-4.4.2/Zend/zend_compile.c	2006-07-13 14:00:25.000000000 +0200
+diff -Nurp php-4.4.4.orig/Zend/zend_compile.c php-4.4.4/Zend/zend_compile.c
+--- php-4.4.4.orig/Zend/zend_compile.c	2006-02-23 19:07:16.000000000 +0100
++++ php-4.4.4/Zend/zend_compile.c	2006-08-31 15:14:33.000000000 +0200
 @@ -37,6 +37,9 @@ ZEND_API zend_compiler_globals compiler_
  ZEND_API zend_executor_globals executor_globals;
  #endif
@@ -225,9 +283,9 @@ diff -Nurp php-4.4.2.orig/Zend/zend_compile.c php-4.4.2/Zend/zend_compile.c
  
  static void build_runtime_defined_function_key(zval *result, zval *name, zend_op *opline TSRMLS_DC)
  {
-diff -Nurp php-4.4.2.orig/Zend/zend_compile.h php-4.4.2/Zend/zend_compile.h
---- php-4.4.2.orig/Zend/zend_compile.h	2006-01-01 14:46:49.000000000 +0100
-+++ php-4.4.2/Zend/zend_compile.h	2006-07-13 14:00:25.000000000 +0200
+diff -Nurp php-4.4.4.orig/Zend/zend_compile.h php-4.4.4/Zend/zend_compile.h
+--- php-4.4.4.orig/Zend/zend_compile.h	2006-01-01 14:46:49.000000000 +0100
++++ php-4.4.4/Zend/zend_compile.h	2006-08-31 15:14:33.000000000 +0200
 @@ -40,6 +40,10 @@
  #define DEC_BPC(op_array)	if (CG(interactive)) { ((op_array)->backpatch_count--); }
  #define HANDLE_INTERACTIVE()  if (CG(interactive)) { execute_new_code(TSRMLS_C); }
