[evol] updated prepare_test_sources scripts (we really should merge all this crap
git-svn-id: https://rcs.lan.proformatique.com/svn/xivo/trunk@8197 dc85baef-7018-0410-bfbd-8a639da648bb

diff --git a/app_conference/prepare_test_sources b/app_conference/prepare_test_sources
--- a/app_conference/prepare_test_sources
+++ b/app_conference/prepare_test_sources
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-. sources.pkg
+. ./sources.pkg
 
 VER=$(cat SOURCE-VERSION)
 
@@ -10,6 +10,11 @@ if [ -n "${DFSG_EXCLUDE_PATTERNS}" ]; then
 	FILENAME="${PKG_NAME}_${VER}+dfsg.orig.tar.gz"
 else
 	FILENAME="${PKG_NAME}_${VER}.orig.tar.gz"
+fi
+
+if [ ! -e ${DEST_PATH}/${FILENAME} ]; then
+	echo "The corresponding tarball is missing (${FILENAME})" >&2
+	exit 1
 fi
 
 rm -rf tmp
diff --git a/dahdi-linux/prepare_test_sources b/dahdi-linux/prepare_test_sources
--- a/dahdi-linux/prepare_test_sources
+++ b/dahdi-linux/prepare_test_sources
@@ -12,6 +12,11 @@ else
 	FILENAME="${PKG_NAME}_${VER}.orig.tar.gz"
 fi
 
+if [ ! -e ${DEST_PATH}/${FILENAME} ]; then
+	echo "The corresponding tarball is missing (${FILENAME})" >&2
+	exit 1
+fi
+
 rm -rf tmp
 mkdir tmp
 tar xz -C tmp -f ${DEST_PATH}/${FILENAME}
diff --git a/dahdi-tools/prepare_test_sources b/dahdi-tools/prepare_test_sources
--- a/dahdi-tools/prepare_test_sources
+++ b/dahdi-tools/prepare_test_sources
@@ -1,6 +1,6 @@
 #!/bin/sh
 
-. sources.pkg
+. ./sources.pkg
 
 VER=$(cat SOURCE-VERSION)
 
@@ -12,12 +12,17 @@ else
 	FILENAME="${PKG_NAME}_${VER}.orig.tar.gz"
 fi
 
+if [ ! -e ${DEST_PATH}/${FILENAME} ]; then
+	echo "The corresponding tarball is missing (${FILENAME})" >&2
+	exit 1
+fi
+
 rm -rf tmp
 mkdir tmp
 tar xz -C tmp -f ${DEST_PATH}/${FILENAME}
 
-if [ -e ../../patches ]; then
-  if [ -e ../../patches/classic ]; then
+if [ -e patches ]; then
+  if [ -e patches/classic ]; then
     PATCH_DIR="../../patches/classic"
   else
     PATCH_DIR="../../patches"
